module.exports = {
  "paragraph": require('substance/ui/nodes/paragraph_component'),
  "heading": require('substance/ui/nodes/heading_component'),
  "blockquote": require('substance/ui/nodes/blockquote_component'),
  "codeblock": require('substance/ui/nodes/codeblock_component'),
  "embed": require('substance/ui/nodes/embed_component'),
  "image": require('substance/ui/nodes/image_component'),
  "table": require('substance/ui/nodes/table_component'),
  "image_figure": require('substance/ui/nodes/figure_component'),
  "table_figure": require('substance/ui/nodes/figure_component'),
  "unsupported_node": require('substance/ui/nodes/unsupported_node'),
  "include": require('substance/ui/nodes/include_component'),
  "bib_item_citation": require('./citation_component'),
  "image_figure_citation": require('./citation_component'),
  "table_figure_citation": require('./citation_component'),
};
